### PR TITLE
Change publication group to org.quiltmc

### LINKED ISSUE #22: Move to org.quiltmc group
Right now, Quilt's fork of enigma doesn't have distinct maven coordinates so it could overlap with other versions. Switching to the `org.quiltmc` group makes it clear that other projects are using this fork (as opposed to one of the many others)

### PR DESCRIPTION
**Pull request by ByMartrixx**
Closes #22

### CODE REVIEW

**Review by ix0rai — APPROVED** [review]
should we consider changing the code package too?

**Comment by ByMartrixx** [comment]
We'd break a lot of stuff if we moved the existing packages now. We might want to wait for #13 too, which would justify moving most if not everything

**Comment by ix0rai** [comment]
good point!
I feel like the QMT migration is a great opportunity to migrate things
I'll leave a comment on that issue

**Comment by OroArmor** [comment]
Id even say wait until enigma is merged into qmt

**Pull request merged**
