### PR TITLE
Fix `StringIndexOutOfBoundsException` when parsing recent files

### PR DESCRIPTION
**Pull request by PiTheGuy**

### CODE REVIEW

**Comment by ix0rai** [comment]
can you share the config file you used to reproduce this?

**Comment by PiTheGuy** [comment]
Where do I find that?

**Comment by PiTheGuy** [comment]
I don't know what file you want so here's the whole folder
[config.zip](https://github.com/user-attachments/files/16698490/config.zip)

**Comment by ix0rai** [comment]
thanks!

**Pull request merged**
