### PR TITLE
fix some docker-related issues

### PR DESCRIPTION
**Pull request by ix0rai**
- no more stupid structure docker opening when you open a class
- preserve docker size when they are being opened
- fix right dock opening too small

### CODE REVIEW

**Review by ByMartrixx — APPROVED** [review]
Rip structure docker opening alongside class :pensive:

**Comment by ByMartrixx** [comment]
Wait, is the docker updated when changing classes with it open?

**Review by ByMartrixx — CHANGES_REQUESTED** [review]
Nope, it isn't updated, please fix - calling `Gui#updateStructure` where `#showStructure` was called before should be enough, I think

**Comment by ix0rai** [comment]
whoops

**Review by ByMartrixx — APPROVED** [review]

**Pull request merged**
